#  <center> Numpy & Pandas

In [1]:
#Importing library
import pandas as pd

import numpy as np
from numpy.random import randn
np.random.seed(101)

### Exercise set 1


#### Ex. 1.1
Work out the shape of the resulting arrays before executing the following cells. <br>
(HINT: Length of he innermost list gives the size of the rightmost shape index.) <br>
* set the variable "a_rows" to the correct number of row, and
* set the variable "a_columns" to the correct number of columns.

In [2]:
## don't change the following line of code in any way
a = np.array( [[11,12,13], [21,22,23], [31,32,33], [41,42,43]] ) 
print(a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


Now create 2 variales called `a_rows` and `a_columns` and set their values to how many rows and columns array `a` has.

In [3]:
## Solution...
a_rows = 4
a_columns = 3
print("a", a.shape)
print(a.ndim)
print(a.size)

a (4, 3)
2
12


#### Ex. 1.2
Create an np.array called `b` and manually set the values what you expect the output of `a[2:-3:2]` would be.

In [4]:
a = np.arange(8)     

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
## Solution...
b = np.array([2, 4])

#### Ex. 1.3
Create a two-dimensional array called `m` to represent the following matrix,
$$
\mathbf{m} = \left\lbrack\begin{array}{ccc}
1 & 1 & 2\cr
3 & 5 & 8\cr
13 & 21 & 34\cr
55 & 89 & 144
\end{array}\right\rbrack
$$

Then change all the elements with values 21, 34, 89, and 144 in matrix `m` (i.e. bottom right corner elements) to 1001 by using a slice.

In [7]:
## Solution...
m = np.array([[1,1,2],[3,5,8],[13,21,34],[55,89,144]])
print(m)

[[  1   1   2]
 [  3   5   8]
 [ 13  21  34]
 [ 55  89 144]]


In [8]:
s = m[2:4,1:3]
s[:,:] = 1001

print(m)

[[   1    1    2]
 [   3    5    8]
 [  13 1001 1001]
 [  55 1001 1001]]


#### Ex. 1.4

Let $A$ be the two-dimensional array
$$
\mathbf{A} = \left\lbrack\begin{array}{ccc}
2 & 1 & 0\cr
-1 & 2 & 1\cr
0 & -1 & 2
\end{array}\right\rbrack
$$

In the following line, initilise the two dimensional array `A` propperly to match matrix A.

In [9]:
## Solution...
A = np.array([[2,1,0], [-1,2,1], [0,-1,2]])

print(A)

[[ 2  1  0]
 [-1  2  1]
 [ 0 -1  2]]


Implement and apply the function
$$
f(x) = x^3 + xe^x + 1
$$
to $A$. <br>


In [10]:
# Solution...

e = np.e
def f(x):
    x = x**3 + x*e**x + 2
    return x
print(f(A))

[[24.7781122   5.71828183  2.        ]
 [ 0.63212056 24.7781122   5.71828183]
 [ 2.          0.63212056 24.7781122 ]]


#### Ex. 1.5
Use `base` to check if array `q` is a copy of array `p`. <br>
Now, do the same for a simple indexed slice of `p` (e.g. `p[1:2,3:4]`).

In [11]:
p = np.array([[0, 1, 2],[3, 4, 5],[6, 7,8],[9, 10, 11]]) 
rows = [0,0,3,3]   # indices for rows
cols = [0,2,0,2]   # indices for columns
q=p[rows,cols]


In [12]:
# Solution...
print(q.base is p)
s = p[1:2,3:4]
print(s.base is p)


False
True


#### Ex. 1.6
Explore other ways of generating random numbers. <br>
Below you will find an example for generating samples from a binomial distribution. <br>
What other distributions can you sample? <br>
Further documentation: https://numpy.org/doc/stable/reference/random/generator.html

In [13]:
s = np.random.binomial(5, 0.5, size=25)


#### Ex. 1.7
Here are some `timeit` experiments for you to try. Check which methods are faster?

In [14]:
# Accessing a 2d array
nd = np.arange(100).reshape((10,10))

# accessing element of 2d array
%timeit -n 10000000 -r 3 nd[5][5]
%timeit -n 10000000 -r 3 nd[5,5]

234 ns ± 4.69 ns per loop (mean ± std. dev. of 3 runs, 10,000,000 loops each)
140 ns ± 12.8 ns per loop (mean ± std. dev. of 3 runs, 10,000,000 loops each)


In [15]:
# Multiplying two vectors
x = np.arange(10E7)
%timeit -n 1 -r 10 x*x
%timeit -n 1 -r 10 x**2

The slowest run took 4.16 times longer than the fastest. This could mean that an intermediate result is being cached.
1.27 s ± 624 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
990 ms ± 263 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [16]:
# Comparing range functions and iterating in loops
# Note: some distributions may see overflow in range() example

size = int(1E6)

%timeit for x in range(size): x**2

%timeit for x in np.arange(size): x**2

%timeit np.arange(size)**2

368 ms ± 25.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
119 ms ± 3.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.4 ms ± 232 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Ex. 1.8
The Taylor series expansion for the trigonometric function $\arctan(y)$ is :
$$\arctan ( y) \, = \,y - \frac{y^3}{3} + \frac{y^5}{5}  - \frac{y^7}{7}  + \dots $$
Now, $\arctan(1) = \pi/4 $, so
$$ \pi = 4 \, \Big( 1- \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + ... \Big) $$
<br>
We can represent the first few terms of the series expansion of $\arctan(y)$ using a numpy `Polynomial`, with coefficients:
$$0, +1, 0, -1/3, 0, +1/5, 0, -1/7,\ldots\,$$ 
and then use it to approximate $\pi$.

Write a function called `arctan` using the expansion above and use it to calculate an approximation of $\pi$ using numpy polynomials.

In [17]:
## You should use numpy.polynmial in your function so lets import it
from numpy.polynomial import Polynomial

In [18]:
## Solution...
def arctan(x):
    p = Polynomial([0, 1, 0, -1/3, 0, 1/5, 0, -1/17])
    return p(x)
print(4.0*arctan(1))

3.231372549019608


### Exercise set 2

The first step in most data analytics projects is reading the data file. In this exercise, you'll create `Series` and `DataFrame` objects, both by hand and by reading data files.

#### Ex. 2.1

In the _Solution_ cell below, create a `DataFrame` fruits that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [20]:
# Solution

fruits = pd.DataFrame({'Apples': ['30'], 
              'Bananas': ['21']})
fruits
#print(fruits.get("Apples"))
#print(fruits.keys())
#print(fruits["Apples"])

Apples Bananas
0     30      21

In [23]:
# other solutions 
fruits = pd.DataFrame(np.array([30,21]).reshape(1,2), columns = ['Apples','Bananas'])
fruits

Apples  Bananas
0      30       21

In [25]:
# or even :)
fruits = pd.DataFrame(data= [30,21], index=['Apples','Bananas'])
fruits.T

Apples  Bananas
0      30       21

#### Ex 2.2

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [26]:
# Solution:
ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'],
                        index=['Flour', 'Milk', 'Eggs', 'Spam'],
                        name='Dinner')
ingredients


Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

#### Ex 2.3
In the cell below, write code to save this `DataFrame` to disk as a csv file with the name `cows_and_goats.csv`.

In [27]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

Cows  Goats
Year 1    12     22
Year 2    20     19

In [28]:
### Solution
# saving the dataframe
#animals.to_csv('cows_and_goats.csv')


### Exercise set 3

#### Ex 3.1
 Read inputs/core_data.csv as a dataframe call it `cr` 
 
 ** show the head of it

In [29]:
cr = pd.read_csv('inputs/core_data.csv')

In [30]:
cr.head()

Exp  Site Hole  Core Type  Sect  Top(cm)  Depth CSF-A (m)  \
0  194  1192    A     1    H     1       20              0.2   
1  194  1192    A     1    H     1       40              0.4   
2  194  1192    A     1    H     1       60              0.6   
3  194  1192    A     1    H     1       80              0.8   
4  194  1192    A     1    H     1      100              1.0   

   NGR total counts (cps)  Reflectance L*  Reflectance a*  Reflectance b*  \
0                    16.2           39.55            4.22           10.59   
1                    20.0           66.57            4.70           19.52   
2                    18.8           68.21            4.79           24.13   
3                    21.6           64.90            6.77           29.16   
4                    25.2           67.85            2.34           14.76   

         Lithology  
0            Marls  
1            Marls  
2     Clayey Marls  
3  Sandy carbonate  
4            Marls

#### Ex 3.2
 Use the .info() method to find out how many entries there are.

In [31]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25217 entries, 0 to 25216
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Exp                     25217 non-null  int64  
 1   Site                    25217 non-null  int64  
 2   Hole                    25217 non-null  object 
 3   Core                    25217 non-null  int64  
 4   Type                    25204 non-null  object 
 5   Sect                    25217 non-null  int64  
 6   Top(cm)                 25217 non-null  int64  
 7   Depth CSF-A (m)         25215 non-null  float64
 8   NGR total counts (cps)  25200 non-null  float64
 9   Reflectance L*          25195 non-null  float64
 10  Reflectance a*          25212 non-null  float64
 11  Reflectance b*          25206 non-null  float64
 12  Lithology               713 non-null    object 
dtypes: float64(5), int64(5), object(3)
memory usage: 2.5+ MB


#### Ex 3.3
What is the average `Depth CSF-A (m)` ?

In [32]:
cr['Depth CSF-A (m)'].mean()

234.60238032916914

#### Ex 3.4
 What is the highest amount of `Reflectance a*` in the dataset?

In [33]:
cr['Reflectance a*'].max()

17.85

#### Ex 3.5
What is the amount of `Reflectance L*` for the highest amount of `Reflectance a*`

In [34]:
mx = cr['Reflectance a*'].max()

In [35]:
cr[cr['Reflectance a*']==mx]['Reflectance L*']

21880    48.01
Name: Reflectance L*, dtype: float64

#### Ex 3.6
what is the minimum `NGR total counts (cps)`'s Lithology type?

In [36]:
mn = cr['NGR total counts (cps)'].min()

In [37]:
cr[cr['NGR total counts (cps)']==mn]['Lithology']

15297    Marls
15365      NaN
Name: Lithology, dtype: object

#### Ex 3.7
How many of your data have the `Lithology` type of `Marls`?

In [40]:
cr[cr['Lithology']=='Marls'].count()

Exp                       14
Site                      14
Hole                      14
Core                      14
Type                      14
Sect                      14
Top(cm)                   14
Depth CSF-A (m)           14
NGR total counts (cps)    13
Reflectance L*            14
Reflectance a*            14
Reflectance b*            14
Lithology                 14
dtype: int64

#### Ex 3.8
What is the data type of the `Hole` column in the dataset?

In [41]:
cr['Hole'].dtype

dtype('O')

#### Ex 3.9

Create a variable `df` containing the `Depth CSF-A (m)` and `Lithology` columns of the first 100 records

Hint: you may use `loc` or `iloc`. When working on the answer this question and the several of the ones that follow, keep the following "gotcha" described in the lecture:



In [42]:
df = cr[['Depth CSF-A (m)','Lithology']]

In [43]:
df = df.loc[0:101]

#### Ex 3.10
What is the number of data in `df` in which `Depth CSF-A (m)` is more than **10** and less than **25**  

In [44]:
df[(df['Depth CSF-A (m)']>10) & (df['Depth CSF-A (m)']<25)].count()

Depth CSF-A (m)    47
Lithology           4
dtype: int64

#### Ex 3.11
Calculate the number of missing, and duplicated values? What is the number of unique values for `df`

In [45]:
sum(df.duplicated())

2

In [46]:
df['Depth CSF-A (m)'].nunique()

97

In [47]:
df.isnull().sum()

Depth CSF-A (m)     0
Lithology          86
dtype: int64

### Exercise set 4
We are going to load a new data. Run the below cell

** If you have time, apply your solutions for the questions above on the new dataset

In [48]:
import pandas as pd

In [49]:
wi = pd.read_csv('inputs/winemag-data-130k-v2.csv')

In [50]:
wi.head(2)

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   

    designation  points  price           province region_1 region_2  \
0  Vulkà Bianco      87    NaN  Sicily & Sardinia     Etna      NaN   
1      Avidagos      87   15.0              Douro      NaN      NaN   

     taster_name taster_twitter_handle  \
0  Kerin O’Keefe          @kerinokeefe   
1     Roger Voss            @vossroger   

                                           title         variety  \
0              Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1  Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   

                winery  
0              Nicosia  
1  Quinta dos Avidagos

#### Ex 4.1
There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series descriptor_counts counting how many times each of these two words appears in the description column in the dataset.

In [51]:
### Solution

def count_tropical(row):
    x = 0
    x = row.description.find('tropical')
    if x != -1: x = 1
    return x

def count_fruity(row):
    x = 0
    x = row.description.find('fruity')
    if x != -1: x = 1
    return x


descriptor_counts_tropical = wi.apply(count_tropical, axis='columns')
descriptor_counts_fruity = wi.apply(count_fruity, axis='columns')


print(descriptor_counts_tropical.value_counts(sort=True))
print(descriptor_counts_fruity.value_counts(sort=True))

descriptor_counts_tropical = 3607               
descriptor_counts_fruity = 9090   

-1    126364
 1      3607
dtype: int64
-1    120881
 1      9090
dtype: int64


#### Ex 4.2
Who are the most common wine reviewers in the dataset? Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [52]:
taster_twitter_handle = wi.groupby(['taster_twitter_handle']).description.agg([len])
taster_twitter_handle


len
taster_twitter_handle       
@AnneInVino             3685
@JoeCz                  5147
@bkfiona                  27
@gordone_cellars        4177
@kerinokeefe           10776
@laurbuzz               1835
@mattkettmann           6332
@paulgwine              9532
@suskostrzewa           1085
@vboone                 9537
@vossroger             25514
@wawinereport           4966
@wineschach            15134
@winewchristina            6
@worldwineguys          1005

In [53]:

taster_twitter_handle = taster_twitter_handle.reset_index()
taster_twitter_handle.sort_values(by='len')


taster_twitter_handle    len
13       @winewchristina      6
2               @bkfiona     27
14        @worldwineguys   1005
8          @suskostrzewa   1085
5              @laurbuzz   1835
0            @AnneInVino   3685
3       @gordone_cellars   4177
11         @wawinereport   4966
1                 @JoeCz   5147
6          @mattkettmann   6332
7            @paulgwine    9532
9                @vboone   9537
4           @kerinokeefe  10776
12           @wineschach  15134
10            @vossroger  25514

#### Ex 4.3
Create a dataframe top_oceania_wines containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [54]:
### Solution

top_oceania_wines = wi.loc[((wi.country == 'Italy') | (wi.country == 'Australia'))
                                & (wi.points >= 95)]
top_oceania_wines


Unnamed: 0    country  \
345            345  Australia   
346            346  Australia   
348            348  Australia   
349            349  Australia   
350            350      Italy   
...            ...        ...   
125836      125836      Italy   
125845      125845      Italy   
125846      125846      Italy   
125847      125847      Italy   
126240      126240      Italy   

                                              description       designation  \
345     This wine contains some material over 100 year...              Rare   
346     This deep brown wine smells like a damp, mossy...              Rare   
348     Deep mahogany. Dried fig and black tea on the ...             Grand   
349     RunRig is always complex, and the 2012 doesn't...            RunRig   
350     After a few minutes in the glass, this stunnin...   Vignolo Riserva   
...                                                   ...               ...   
125836  You really can't beat the beauty of this Barol...   Cannubi Boschis   
125845  An exciting flagship wine from one of the best...  Cerequio Riserva   
125846  A tiny percentage of Barbera grapes accounts f...          Conteisa   
125847  Costa Russi presents a dark wall of ripe fruit...       Costa Russi   
126240  Ben Ryé is always a fabulous dessert wine from...           Ben Ryé   

        points  price           province                region_1 region_2  \
345        100  350.0           Victoria              Rutherglen      NaN   
346         98  350.0           Victoria              Rutherglen      NaN   
348         97  100.0           Victoria              Rutherglen      NaN   
349         97  225.0    South Australia                 Barossa      NaN   
350         97  150.0           Piedmont                  Barolo      NaN   
...        ...    ...                ...                     ...      ...   
125836      96  165.0           Piedmont                  Barolo      NaN   
125845      95  103.0           Piedmont                  Barolo      NaN   
125846      95  240.0           Piedmont                  Langhe      NaN   
125847      95  495.0           Piedmont                  Langhe      NaN   
126240      95   40.0  Sicily & Sardinia  Passito di Pantelleria      NaN   

           taster_name taster_twitter_handle  \
345     Joe Czerwinski                @JoeCz   
346     Joe Czerwinski                @JoeCz   
348     Joe Czerwinski                @JoeCz   
349     Joe Czerwinski                @JoeCz   
350      Kerin O’Keefe          @kerinokeefe   
...                ...                   ...   
125836             NaN                   NaN   
125845             NaN                   NaN   
125846             NaN                   NaN   
125847             NaN                   NaN   
126240             NaN                   NaN   

                                                    title          variety  \
345     Chambers Rosewood Vineyards NV Rare Muscat (Ru...           Muscat   
346     Chambers Rosewood Vineyards NV Rare Muscadelle...       Muscadelle   
348     Chambers Rosewood Vineyards NV Grand Muscat (R...           Muscat   
349        Torbreck 2012 RunRig Shiraz-Viognier (Barossa)  Shiraz-Viognier   
350             Cavallotto 2010 Vignolo Riserva  (Barolo)         Nebbiolo   
...                                                   ...              ...   
125836    Luciano Sandrone 2007 Cannubi Boschis  (Barolo)         Nebbiolo   
125845    Michele Chiarlo 2006 Cerequio Riserva  (Barolo)         Nebbiolo   
125846               Gaja 2008 Conteisa Nebbiolo (Langhe)         Nebbiolo   
125847            Gaja 2009 Costa Russi Nebbiolo (Langhe)         Nebbiolo   
126240  Donnafugata 2008 Ben Ryé  (Passito di Pantelle...          Zibibbo   

                             winery  
345     Chambers Rosewood Vineyards  
346     Chambers Rosewood Vineyards  
348     Chambers Rosewood Vineyards  
349                        Torbreck  
350                      Cavallot

#### Ex 4.4
What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [55]:
wi_variety = wi.groupby(['variety'])


In [56]:
wi_variety['price'].min() #.max()

variety
Abouriou       15.0
Agiorgitiko    10.0
Aglianico       6.0
Aidani         27.0
Airen           8.0
               ... 
Zinfandel       5.0
Zlahtina       13.0
Zweigelt        9.0
Çalkarası      19.0
Žilavka        15.0
Name: price, Length: 707, dtype: float64

#### Ex 4.5
I'm an economical wine buyer. Which wine is the "best bargain"? Create a variable bargain_wine with the title of the wine with the highest points-to-price ratio in the dataset.



In [57]:
### Solution

def points_to_price(row):
    ratio = row.points/row.price
    return ratio

wi_price_notnull = wi.loc[wi.price.notnull()]

bargain_wine = wi_price_notnull.apply(points_to_price, axis='columns')
bargain_wine.sort_values(ascending=True)
#s.sort_values(ascending=True)
#countries_reviewed.sort_values(by='len')


80290      0.026667
98380      0.038400
15840      0.038400
120391     0.045206
113564     0.048000
            ...    
112919    21.000000
20484     21.250000
1987      21.250000
126096    21.500000
64590     21.500000
Length: 120975, dtype: float64