#  <center> Numpy & Pandas

In [3]:
#Importing library
import pandas as pd

import numpy as np
from numpy.random import randn
np.random.seed(101)

In [ ]:
print('Hello World')

### Exercise set 1

#### Ex. 1.1
Work out the shape of the resulting arrays before executing the following cells. <br>
(HINT: Length of he innermost list gives the size of the rightmost shape index.) <br>
* set the variable "a_rows" to the correct number of row, and
* set the variable "a_columns" to the correct number of columns.

In [4]:
## don't change the following line of code in any way
a = np.array( [[11,12,13], [21,22,23], [31,32,33], [41,42,43]] ) 
print(a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


Now create 2 variales called `a_rows` and `a_columns` and set their values to how many rows and columns array `a` has.

In [5]:
a_rows = 4
a_columns = 3 

#### Ex. 1.2
Create an np.array called `b` and manually set the values what you expect the output of `a[2:-3:2]` would be.

In [9]:
a = np.arange(8)  
a[2:-3:2]

array([2, 3, 4])

In [ ]:
b = np.array([2,4])


#### Ex. 1.3
Create a two-dimensional array called `m` to represent the following matrix,
$$
\mathbf{m} = \left\lbrack\begin{array}{ccc}
1 & 1 & 2\cr
3 & 5 & 8\cr
13 & 21 & 34\cr
55 & 89 & 144
\end{array}\right\rbrack
$$

Then change all the elements with values 21, 34, 89, and 144 in matrix `m` (i.e. bottom right corner elements) to 1001 by using a slice.

In [10]:
m = [[1,1,2],[3,5,8],[13,21,34],[55,89,144]]

In [11]:
m[2][1], m[2][2],m[3][1],m[3][2] = 1001,1001,1001,1001

#### Ex. 1.4

Let $A$ be the two-dimensional array
$$
\mathbf{A} = \left\lbrack\begin{array}{ccc}
2 & 1 & 0\cr
-1 & 2 & 1\cr
0 & -1 & 2
\end{array}\right\rbrack
$$

In the following line, initilise the two dimensional array `A` propperly to match matrix A.

In [14]:
A = np.array([[2,1,0],[-1,2,1],[0,-1,2]])

Implement and apply the function
$$
f(x) = x^3 + xe^x + 1
$$
to $A$. <br>

In [17]:
f = lambda x : x**3 +x*np.exp(x) +1
print (f(A))

[[23.7781122   4.71828183  1.        ]
 [-0.36787944 23.7781122   4.71828183]
 [ 1.         -0.36787944 23.7781122 ]]


#### Ex. 1.5
Use `base` to check if array `q` is a copy of array `p`. <br>
Now, do the same for a simple indexed slice of `p` (e.g. `p[1:2,3:4]`).

In [18]:
p = np.array([[0, 1, 2],[3, 4, 5],[6, 7,8],[9, 10, 11]]) 
rows = [0,0,3,3]   # indices for rows
cols = [0,2,0,2]   # indices for columns
q=p[rows,cols]

In [25]:
p

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
q

array([ 0,  2,  9, 11])

In [23]:
p[0][0].base is q[0].base

True

In [28]:
p[1:2,0:2]

array([[3, 4]])

#### Ex. 1.6
Explore other ways of generating random numbers. <br>
Below you will find an example for generating samples from a binomial distribution. <br>
What other distributions can you sample? <br>
Further documentation: https://numpy.org/doc/stable/reference/random/generator.html

In [29]:
s = np.random.binomial(5, 0.5, size=25)

#### Ex. 1.7
Here are some `timeit` experiments for you to try. Check which methods are faster?

In [36]:
nd[[0,1],[0,1]]

array([ 0, 11])

In [37]:
nd

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
# Accessing a 2d array
nd = np.arange(100).reshape((10,10))

# accessing element of 2d array
%timeit -n 10000000 -r 3 nd[5][5]
%timeit -n 10000000 -r 3 nd[5,5]   #这个快一倍

110 ns ± 1.36 ns per loop (mean ± std. dev. of 3 runs, 10,000,000 loops each)
61.6 ns ± 0.0778 ns per loop (mean ± std. dev. of 3 runs, 10,000,000 loops each)


In [31]:
# Multiplying two vectors
x = np.arange(10E7)
%timeit -n 1 -r 10 x*x
%timeit -n 1 -r 10 x**2

90.3 ms ± 24.8 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
81.1 ms ± 722 µs per loop (mean ± std. dev. of 10 runs, 1 loop each)


In [38]:
# Comparing range functions and iterating in loops
# Note: some distributions may see overflow in range() example

size = int(1E6)

%timeit for x in range(size): x**2

%timeit for x in np.arange(size): x**2

%timeit np.arange(size)**2    

# 直接在矩阵上做运算，因为他这里默认的就是对每个元素

193 ms ± 167 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
52.2 ms ± 68.1 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.11 ms ± 3.72 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Ex. 1.8
The Taylor series expansion for the trigonometric function $\arctan(y)$ is :
$$\arctan ( y) \, = \,y - \frac{y^3}{3} + \frac{y^5}{5}  - \frac{y^7}{7}  + \dots $$
Now, $\arctan(1) = \pi/4 $, so
$$ \pi = 4 \, \Big( 1- \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + ... \Big) $$
<br>
We can represent the first few terms of the series expansion of $\arctan(y)$ using a numpy `Polynomial`, with coefficients:
$$0, +1, 0, -1/3, 0, +1/5, 0, -1/7,\ldots\,$$ 
and then use it to approximate $\pi$.

Write a function called `arctan` using the expansion above and use it to calculate an approximation of $\pi$ using numpy polynomials.

In [39]:
## You should use numpy.polynmial in your function so lets import it
from numpy.polynomial import Polynomial

In [54]:
def arctan(y):
    ind = [ (-1)**(x+1) * 1/(2*x-1) for x in range(1,100)]
    a = [0]
    return Polynomial([a]+ind)(y)

In [55]:
arctan(1)

array([0.78792335])

### Exercise set 2

The first step in most data analytics projects is reading the data file. In this exercise, you'll create `Series` and `DataFrame` objects, both by hand and by reading data files.

#### Ex. 2.1

In the _Solution_ cell below, create a `DataFrame` fruits that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [61]:
df = pd.DataFrame(np.array([[30,21]]),index = [0], columns = ['Apples','Bananas'])
df

Apples  Bananas
0      30       21

#### Ex 2.2

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [64]:
ingredients = pd.Series(data = ['4 cups','1 cup','2 large', '1 can'], index = ['Flour','Milk','Eggs','Spam'])

In [65]:
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
dtype: object

#### Ex 2.3
In the cell below, write code to save this `DataFrame` to disk as a csv file with the name `cows_and_goats.csv`.

In [66]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

Cows  Goats
Year 1    12     22
Year 2    20     19

In [67]:
animals.to_csv('cows_and_goats.csv')

### Exercise set 3

#### Ex 3.1
 Read inputs/core_data.csv as a dataframe call it `cr` 
 
 ** show the head of it

In [68]:
cr  = pd.read_csv('inputs/core_data.csv')

In [70]:
cr.head()

Exp  Site Hole  Core Type  Sect  Top(cm)  Depth CSF-A (m)  \
0  194  1192    A     1    H     1       20              0.2   
1  194  1192    A     1    H     1       40              0.4   
2  194  1192    A     1    H     1       60              0.6   
3  194  1192    A     1    H     1       80              0.8   
4  194  1192    A     1    H     1      100              1.0   

   NGR total counts (cps)  Reflectance L*  Reflectance a*  Reflectance b*  \
0                    16.2           39.55            4.22           10.59   
1                    20.0           66.57            4.70           19.52   
2                    18.8           68.21            4.79           24.13   
3                    21.6           64.90            6.77           29.16   
4                    25.2           67.85            2.34           14.76   

         Lithology  
0            Marls  
1            Marls  
2     Clayey Marls  
3  Sandy carbonate  
4            Marls

#### Ex 3.2
 Use the .info() method to find out how many entries there are.

In [71]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25217 entries, 0 to 25216
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Exp                     25217 non-null  int64  
 1   Site                    25217 non-null  int64  
 2   Hole                    25217 non-null  object 
 3   Core                    25217 non-null  int64  
 4   Type                    25204 non-null  object 
 5   Sect                    25217 non-null  int64  
 6   Top(cm)                 25217 non-null  int64  
 7   Depth CSF-A (m)         25215 non-null  float64
 8   NGR total counts (cps)  25200 non-null  float64
 9   Reflectance L*          25195 non-null  float64
 10  Reflectance a*          25212 non-null  float64
 11  Reflectance b*          25206 non-null  float64
 12  Lithology               713 non-null    object 
dtypes: float64(5), int64(5), object(3)
memory usage: 2.5+ MB


#### Ex 3.3
What is the average `Depth CSF-A (m)` ?

In [74]:
cr.iloc[:,7].mean()

234.60238032916914

#### Ex 3.4
 What is the highest amount of `Reflectance a*` in the dataset?

In [75]:
cr.iloc[:,10].max()

17.85

#### Ex 3.5
What is the amount of `Reflectance L*` for the highest amount of `Reflectance a*`

In [80]:
cr[cr.iloc[:,10].max()==cr.iloc[:,10]].iloc[:,9]

21880    48.01
Name: Reflectance L*, dtype: float64

#### Ex 3.6
what is the minimum `NGR total counts (cps)`'s Lithology type?

In [82]:
cr[cr['NGR total counts (cps)']==cr['NGR total counts (cps)'].min()]['Lithology']

15297    Marls
15365      NaN
Name: Lithology, dtype: object

#### Ex 3.7
How many `Holes` has the `Lithology` type of `Marls`?

In [85]:
cr[cr['Lithology']=='Marls']['Hole'].info()

<class 'pandas.core.series.Series'>
Int64Index: 14 entries, 0 to 15298
Series name: Hole
Non-Null Count  Dtype 
--------------  ----- 
14 non-null     object
dtypes: object(1)
memory usage: 224.0+ bytes


#### Ex 3.8
What is the data type of the `Hole` column in the dataset?

In [92]:
cr['Hole'].dtype  #It means: 'O' (Python) objects

dtype('O')

#### Ex 3.9

Create a variable `df` containing the `Depth CSF-A (m)` and `Lithology` columns of the first 100 records

Hint: you may use `loc` or `iloc`. When working on the answer this question and the several of the ones that follow, keep the following "gotcha" described in the lecture:

In [196]:
df = cr[['Depth CSF-A (m)','Lithology']].iloc[0:100]
df

Depth CSF-A (m)        Lithology
0               0.2            Marls
1               0.4            Marls
2               0.6     Clayey Marls
3               0.8  Sandy carbonate
4               1.0            Marls
..              ...              ...
95             25.6              NaN
96             25.8              NaN
97             26.0              NaN
98             26.2              NaN
99             26.4              NaN

[100 rows x 2 columns]

#### Ex 3.10
What is the number of data in `df` in which `Depth CSF-A (m)` is more than **10** and less than **25**

In [110]:
len(df[(df.iloc[:,0]>10) & (df.iloc[:,0]<25)].iloc[:,0])

47

In [151]:
print(df.isnull() == ~df.notnull())

    Depth CSF-A (m)  Lithology
0              True       True
1              True       True
2              True       True
3              True       True
4              True       True
..              ...        ...
95             True       True
96             True       True
97             True       True
98             True       True
99             True       True

[100 rows x 2 columns]


#### Ex 3.11
Calculate the number of missing, and duplicated values? What is the number of unique values for `df`

In [154]:
df.isnull().iloc[:,0].values.any() #CSF has no missing value

False

In [155]:
df.isnull().sum()

Depth CSF-A (m)     0
Lithology          84
dtype: int64

In [146]:
len(df.loc[~df.notnull().iloc[:,1]])

84

In [197]:
df.duplicated().sum()

2

In [166]:
print(df['Depth CSF-A (m)'].value_counts())

4.9     2
1.7     2
4.4     2
10.1    2
4.0     2
       ..
7.2     1
7.0     1
6.8     1
6.6     1
26.4    1
Name: Depth CSF-A (m), Length: 95, dtype: int64


In [192]:
print((df['Depth CSF-A (m)'].value_counts()>1).sum())
print(len(df['Depth CSF-A (m)'].unique()))
print(df['Depth CSF-A (m)'].nunique())

5
95
95


### Exercise set 4
We are going to load a new data. Run the below cell

** If you have time, apply your solutions for the questions above on the new dataset

In [167]:
wi = pd.read_csv('inputs/winemag-data-130k-v2.csv')

#### Ex 4.1
There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series descriptor_counts counting how many times each of these two words appears in the description column in the dataset.

In [169]:
ser = wi['description']

In [187]:
t,f = 0,0
for i in ser:
    if 'tropical' in i.lower():
        t+=1
    if 'fruity' in i.lower():
        f+=1
#     print(i+ '\n')
print(f'{t = }, {f = }')


t = 3800, f = 9455


#### Ex 4.2
Who are the most common wine reviewers in the dataset? Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [199]:
ser2 = wi['taster_twitter_handle']
ser2 

0         @kerinokeefe
1           @vossroger
2          @paulgwine 
3                  NaN
4          @paulgwine 
              ...     
129966             NaN
129967     @paulgwine 
129968      @vossroger
129969      @vossroger
129970      @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

In [219]:
ser2.value_counts()
dic = {}
for i in ser2.value_counts().index:
    dic[i] = ser2.value_counts()[i]
    
dic

{'@vossroger': 25514,
 '@wineschach': 15134,
 '@kerinokeefe': 10776,
 '@vboone': 9537,
 '@paulgwine\xa0': 9532,
 '@mattkettmann': 6332,
 '@JoeCz': 5147,
 '@wawinereport': 4966,
 '@gordone_cellars': 4177,
 '@AnneInVino': 3685,
 '@laurbuzz': 1835,
 '@suskostrzewa': 1085,
 '@worldwineguys': 1005,
 '@bkfiona': 27,
 '@winewchristina': 6}

#### Ex 4.3
Create a dataframe top_oceania_wines containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [233]:
wi_sc = wi[(wi['country']=='Australia') | (wi['country']=='New Zealand') ]
topow = wi_sc[wi_sc['points']>95]
topow

Unnamed: 0    country  \
345            345  Australia   
346            346  Australia   
348            348  Australia   
349            349  Australia   
34502        34502  Australia   
34506        34506  Australia   
39961        39961  Australia   
56953        56953  Australia   
56956        56956  Australia   
56957        56957  Australia   
56959        56959  Australia   
59977        59977  Australia   
67096        67096  Australia   
77028        77028  Australia   
77036        77036  Australia   
77037        77037  Australia   
83357        83357  Australia   
87128        87128  Australia   
109427      109427  Australia   
109434      109434  Australia   
122421      122421  Australia   
122939      122939  Australia   

                                              description  \
345     This wine contains some material over 100 year...   
346     This deep brown wine smells like a damp, mossy...   
348     Deep mahogany. Dried fig and black tea on the ...   
349     RunRig is always complex, and the 2012 doesn't...   
34502   This prodigious wine showcases Barossa's abili...   
34506   If Standish's Relic is the feminine side of Sh...   
39961   As unevolved as they are, the dense and multil...   
56953   This inky, embryonic wine deserves to be cella...   
56956   You may have to scour the country to secure so...   
56957   Thorn Clarke has taken its Shiraz to a new lev...   
56959   Is this the Yin to Grange's Yang? The wines ar...   
59977   This is a top example of the classic Australia...   
67096   Just a tiny serving of this dark nectar will l...   
77028   This has all the size and weight you've come t...   
77036   RWT (unromantically derived from “Red Wine Tri...   
77037   Winemaker Dave Powell is no longer with Torbre...   
83357   A throwback to the monster Shiraz style of old...   
87128   This full-bodied, muscular Shiraz is built for...   
109427  This wine is dark brown in hue with a greenish...   
109434  D'Arenberg's lineup of single-vineyard Shiraze...   
122421  Despite this wine's weight and richness, it re...   
122939  Full-bodied and plush yet vibrant and imbued w...   

                                   designation  points  price  \
345                                       Rare     100  350.0   
346                                       Rare      98  350.0   
348                                      Grand      97  100.0   
349                                     RunRig      97  225.0   
34502                                The Relic      98  135.0   
34506             The Standish Single Vineyard      96  135.0   
39961                                   Grange      96  185.0   
56953                                   Grange      99  850.0   
56956                               Andelmonde      97   95.0   
56957                Ron Thorn Single Vineyard      96   89.0   
56959                            Hill of Grace      96  820.0   
59977                                The Peake      96  150.0   
67096                            Calliope Rare      98   86.0   
77028                                   Grange      98  850.0   
77036                                      RWT      96  150.0   
77037                                   RunRig      96  225.0   
83357                                   Grange      96  500.0   
87128                   Amery Vineyard Block 6      96  120.0   
109427                                    Rare      99  300.0   
109434  The Swinging Malaysian Single Vineyard      96   85.0   
122421                      Amon-Ra Unfiltered      96  110.0   
122939                              The Factor      98  125.0   

               province         region_1 region_2     taster_name  \
345            Victoria       Rutherglen      NaN  Joe Czerwinski   
346            Victoria       Rutherglen      NaN  Joe Czerwinski   
348            Victoria       Rutherglen      NaN  Joe Czerwinski   
349     South Australia          Barossa      NaN  Joe Czerwinski   
345

#### Ex 4.4
What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [243]:
a['price'].size().index  # Notice the .size() method

Index(['Abouriou', 'Agiorgitiko', 'Aglianico', 'Aidani', 'Airen', 'Albana',
       'Albanello', 'Albariño', 'Albarossa', 'Aleatico',
       ...
       'Yapincak', 'Zelen', 'Zibibbo', 'Zierfandler', 'Zierfandler-Rotgipfler',
       'Zinfandel', 'Zlahtina', 'Zweigelt', 'Çalkarası', 'Žilavka'],
      dtype='object', name='variety', length=707)

In [246]:
a = wi.groupby('variety')
df = pd.DataFrame({'Min_price':list(a['price'].min()),'Max_price':list(a['price'].max())}, index = list(a['price'].size().index))

In [247]:
df

Min_price  Max_price
Abouriou          15.0       75.0
Agiorgitiko       10.0       66.0
Aglianico          6.0      180.0
Aidani            27.0       27.0
Airen              8.0       10.0
...                ...        ...
Zinfandel          5.0      100.0
Zlahtina          13.0       16.0
Zweigelt           9.0       70.0
Çalkarası         19.0       19.0
Žilavka           15.0       15.0

[707 rows x 2 columns]

#### Ex 4.5
I'm an economical wine buyer. Which wine is the "best bargain"? Create a variable bargain_wine with the title of the wine with the highest points-to-price ratio in the dataset.

In [255]:
wi_ = wi.set_index('title')

In [256]:
po = wi_['points']
pr = wi_['price']

In [258]:
bargain = po/pr

In [268]:
pd.DataFrame(bargain.values,index = bargain.index)

0
title                                                       
Nicosia 2013 Vulkà Bianco  (Etna)                        NaN
Quinta dos Avidagos 2011 Avidagos Red (Douro)       5.800000
Rainstorm 2013 Pinot Gris (Willamette Valley)       6.214286
St. Julian 2013 Reserve Late Harvest Riesling (...  6.692308
Sweet Cheeks 2012 Vintner's Reserve Wild Child ...  1.338462
...                                                      ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 B...  3.214286
Citation 2004 Pinot Noir (Oregon)                   1.200000
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)  3.000000
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)       2.812500
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caro...  4.285714

[129971 rows x 1 columns]

#### Ex 4.6

`region_1` and `region_2` are pretty uninformative names for locale columns in our wine reviews dataset. Create a copy of `wi` with these columns renamed to `region` and `locale`, respectively.

In [272]:
wi_new = wi.rename(columns = {'region_1' : 'region', 'region_2' : 'locale'})

In [273]:
wi_new

Unnamed: 0   country  \
0                0     Italy   
1                1  Portugal   
2                2        US   
3                3        US   
4                4        US   
...            ...       ...   
129966      129966   Germany   
129967      129967        US   
129968      129968    France   
129969      129969    France   
129970      129970    France   

                                              description  \
0       Aromas include tropical fruit, broom, brimston...   
1       This is ripe and fruity, a wine that is smooth...   
2       Tart and snappy, the flavors of lime flesh and...   
3       Pineapple rind, lemon pith and orange blossom ...   
4       Much like the regular bottling from 2012, this...   
...                                                   ...   
129966  Notes of honeysuckle and cantaloupe sweeten th...   
129967  Citation is given as much as a decade of bottl...   
129968  Well-drained gravel soil gives this wine its c...   
129969  A dry style of Pinot Gris, this is crisp with ...   
129970  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price  \
0                                 Vulkà Bianco      87    NaN   
1                                     Avidagos      87   15.0   
2                                          NaN      87   14.0   
3                         Reserve Late Harvest      87   13.0   
4           Vintner's Reserve Wild Child Block      87   65.0   
...                                        ...     ...    ...   
129966  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
129967                                     NaN      90   75.0   
129968                                   Kritt      90   30.0   
129969                                     NaN      90   32.0   
129970           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 province               region             locale  \
0       Sicily & Sardinia                 Etna                NaN   
1                   Douro                  NaN                NaN   
2                  Oregon    Willamette Valley  Willamette Valley   
3                Michigan  Lake Michigan Shore                NaN   
4                  Oregon    Willamette Valley  Willamette Valley   
...                   ...                  ...                ...   
129966              Mosel                  NaN                NaN   
129967             Oregon               Oregon       Oregon Other   
129968             Alsace               Alsace                NaN   
129969             Alsace               Alsace                NaN   
129970             Alsace               Alsace                NaN   

               taster_name taster_twitter_handle  \
0            Kerin O’Keefe          @kerinokeefe   
1               Roger Voss            @vossroger   
2             Paul Gregutt           @paulgwine    
3       Alexander Peartree                   NaN   
4             Paul Gregutt           @paulgwine    
...                    ...                   ...   
129966  Anna Lee C. Iijima                   NaN   
129967        Paul Gregutt           @paulgwine    
129968          Roger Voss            @vossroger   
129969          Roger Voss            @vossroger   
129970          Roger Voss            @vossroger   

                                                    title         variety  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   
3       St. Julian 2013 Reserve Late Harvest Riesling ...        Riesling   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...      Pinot Noir   
...                                                   ...             ...   
129966  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...        Riesling   
129967                  Citation 2004 P