#  <center> Pandas and Numpy

<div class="alert alert-block alert-danger">

# Terminology

**If it is hard, Do not Panic!**
____

**If it is easy, Do not underestimate it!**

___
**Do write your own code for the exercises -- Do not copy paste!** you will never become good in coding if you read through the lines of others code and copy-paste them. 
___

- There are  series of excercises, both in the morning and afternoon class. At the end of each day, I will put the solutions in Github repo.
 
- There is an [Extra](./Extra.ipynb) notebook, shown in <span style='color:green'> green boxes through this lecture</span>, that can be skipped (by you and me) in the interests of time. If/when you have the time please read through these sections for your general education
    
</div>

# Introduction to Numpy 
* [NumPy](https://numpy.org/) (or Numpy) is a Linear Algebra Library for Python
 NumPy supports:
- Multidimensional arrays (`ndarray`)
- Matrices and linear algebra operations
- Random number generation
- Fourier transforms
- Polynomials
- Tools for integrating with Fortran/C libraries

<div class="alert alert-block alert-info">

## Learning objectives 
- Learn what NumPy arrays are
- Learn basic array manipulations
- Learn what vectorial code is

 </div>

In [1]:
import numpy as np

# Numpy Arrays

### NumPy Arrays overview

* Core (or Standard) Python Library provides lists and 1D arrays (array.array)

  * Lists are general containers for objects
  * Arrays are 1D containers for objects of the same type
  * Limited functionality
  * Some memory and performance overhead associated with these structures

* NumPy provides multidimensional arrays (numpy.ndarray)
  * Can store many elements of the same data type in multiple dimensions
  * cf. Fortran/C/C++ arrays
  * More functionality than Core Python e.g. many conveninent methods for array manipulation
  * Efficient storage and execution

* [Extensive online documentation !](https://docs.scipy.org/doc/numpy/)
Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Using built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [4]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros, ones and identity matrix

Generate arrays of zeros or ones and  identity  matrix

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [10]:
np.linspace(0,20,10)  
# 9 intervels

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand -- from a  <span style="color:blue">UNIFORM</span> distribution
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [11]:
np.random.rand(2)

array([0.81855209, 0.92090142])

In [12]:
np.random.rand(3,3)

array([[0.02593168, 0.51124905, 0.15021135],
       [0.84732222, 0.39268078, 0.54407399],
       [0.06448745, 0.55475534, 0.98143529]])

### randn --  from a <span style="color:blue">normal</span>  distribution
(mean=0, standard deviation=1)

In [13]:
np.random.randn(3)

array([ 0.89912886, -0.46832397, -1.31163436])

### randint 
Return random integers from `low` (inclusive) to `high` (exclusive).

In [14]:
np.random.randint(1,100)

44

In [15]:
np.random.randint(1,100,6)

array([40, 49, 49, 38, 16, 44])

You can create 2d arrays with complex elements by specifying the data type.

In [16]:
alist = [[1, 2, 3], [4, 5, 6]]
mat = np.array(alist, complex)
print(mat)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [17]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
ranarr

array([ 3,  5, 31, 35, 31, 41, 12, 49, 35, 49])

In [20]:
# Examine key array attributes
print("Dimensions ", arr.ndim)   # Number of dimensions
print("Shape      ", arr.shape)  # number of elements in each dimension
print("Size       ", arr.size)   # total number of elements
print("Data type  ", arr.dtype)  # data type of element, 64 bit float (IEEE 754) by default

Dimensions  1
Shape       (25,)
Size        25
Data type   int64


### Reshape
Returns an array containing the same data with a new shape.

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
# Vector
arr.shape

(25,)

In [23]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [24]:
arr.reshape(1,25).shape

(1, 25)

In [25]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [26]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [27]:
arr.dtype

dtype('int64')

### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [29]:
ranarr

array([ 3,  5, 31, 35, 31, 41, 12, 49, 35, 49])

In [28]:
ranarr.max()

49

In [30]:
ranarr.argmax() 
# Return the index of the max element

7

### mean, std

In [31]:
ranarr.std()

16.01530517973354

# NumPy Indexing and Selection
 we will discuss how to select elements or groups of elements from an array.

In [32]:
#Creating sample array
arr = np.arange(2,11)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [33]:
#Get a value at an index
arr[8]

10

In [34]:
#Get values in a range
arr[1:5]

array([3, 4, 5, 6])

In [35]:
#Get values in a range
arr[0:5]

array([2, 3, 4, 5, 6])

In [36]:
arr[:6] 
# 0 to 5

array([2, 3, 4, 5, 6, 7])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [37]:
#Setting a value with index range (Broadcasting)
arr[0:5]=99

#Show
arr

array([99, 99, 99, 99, 99,  7,  8,  9, 10])

In [38]:
# Reset array, 
arr = np.arange(2,11)

#Show
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = 2
a = b
a = 1
b

In [39]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([2, 3, 4, 5, 6, 7])

In [40]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [41]:
arr

array([99, 99, 99, 99, 99, 99,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [42]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [43]:
arr_2d = np.array(([5,7,9],[10,12,14],[15,17,19]))

#Show
arr_2d

array([[ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

In [44]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

10

In [45]:
# Getting individual element value
arr_2d[1,0]

10

In [46]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[ 7,  9],
       [12, 14]])

In [47]:
#Shape bottom row
arr_2d[2] #arr_2d[2,:]

array([15, 17, 19])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [48]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [50]:
arr[arr>=5]

array([ 5,  6,  7,  8,  9, 10])

# NumPy Operations
## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [51]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
arr * arr    #Not array multiplication. just corresponding index

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [53]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/var/folders/wb/x375xcqd3p31cgn8w1m_xggm0000gp/T/ipykernel_18743/2878212635.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
# Also warning, but not an error instead infinity
1/arr

/var/folders/wb/x375xcqd3p31cgn8w1m_xggm0000gp/T/ipykernel_18743/1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [56]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [57]:
def f(x):
    return x**3

x = np.array([1,2,3,4,5,6,7,8,9])
y = f(x)

print(y)

[  1   8  27  64 125 216 343 512 729]


## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [60]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [61]:
np.max(arr) #same as arr.max()

10

In [62]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [63]:
np.log(arr)

/var/folders/wb/x375xcqd3p31cgn8w1m_xggm0000gp/T/ipykernel_18743/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

### Linear algebra with numpy.linalg
 
Numpy provides some linear algebra capabilities, from matrix-vector product to matrix inversion and system solution

In [64]:
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
B = np.array([1,2,1])

print(np.dot(A,B))

[ 8 20 31]


In [70]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [65]:
import numpy.linalg as la

In [66]:
n = la.norm(B)
print(n)

n = la.norm(A)
print(n)

d = la.det(A)
print(d)

2.449489742783178
16.3707055437449
2.999999999999999


And it is possible to solve linear systems, using low level C/Fortran code:

In [67]:
la.solve(A,B)  # A sol = B

array([ 1.66666667, -3.33333333,  2.        ])

In [68]:
A_inv = la.inv(A)
print(A_inv)

[[-2.66666667  2.66666667 -1.        ]
 [ 3.33333333 -4.33333333  2.        ]
 [-1.          2.         -1.        ]]


In [69]:
#The eigen decomposition (of a square matrix) can also be computed:
eival, eivec = la.eig(A)
print(eival)
print(eivec)

[15.55528261 -1.41940876 -0.13587385]
[[-0.24043423 -0.67468642  0.51853459]
 [-0.54694322 -0.23391616 -0.78895962]
 [-0.80190056  0.70005819  0.32964312]]


### Performance

Python has a convenient timing function called `timeit`.

Can use this to measure the execution time of small code snippets.

* From python: `import timeit` and supply code  snippet as a string
* From ipython: can use magic command `%timeit`

By default, `%timeit` loops (repeats) over your code 3 times and outputs the best time. It also tells you how many iterations it ran the code per loop. 
You can specify the number of loops and the number of iterations per loop.
```
%timeit -n <iterations> -r <repeats>  <code_snippet>
```

See

* `%timeit?` for more information
* https://docs.python.org/2/library/timeit.html

# Introduction to Pandas
[Pandas](https://pandas.pydata.org/) is an open source library that's <span style="color:red">built on top of NumPy.</span> 
 The name is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time periods for the same individuals.

- It allows for fast analysis and data cleaning and preparation. It is used for preprocessing machine learning approaches.
- It excels in performance and productivity for the user.
- It has built-in visualization features.
- It can work with data from a wide variety of sources.
- It allows importing data in various formats such as csv, excel, HTML, etc.
- It allows a range of data manipulation operations such as `groupby`, `join`, `merge`, `melt`, `concatenation` as well as data cleaning features such as filling, replacing or imputing null values.
- It is used for timeseries analysis.

<div class="alert alert-block alert-info">

## Learning objectives 
Today we will learn how to use pandas for data analysis. 
- Series
- DataFrames: Creating, reading and writing to `DataFrame`'s.
- Indexing of `DataFrame`'s and how to slice and reference them.
- Operations
- Extract information from your data through summary functions and maps.
- Grouping and sorting data.
- `DataType`'s and handling missing data.
- Renaming Merging,Joining,and Concatenating.
- **Built-in visualization features
- **Timeseries with Pandas
 </div>

In [71]:
#Importing library
import pandas as pd

from numpy.random import randn
np.random.seed(101)

#  Series
A Series is built on top of the NumPy array object.
- A Series can be indexed by a label.
- It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

Let's explore this concept through some examples:

## Creating a Series in diffrent ways

You can convert a **list**, **numpy array**, or **dictionary** to a Series:

In [72]:
labels = ['x','y','z']
my_list = [100,200, 300] #python list
arr = np.array([100,200,300]) #python array
dic = {'x':100,'y':200,'z':300}  #python dictionary

**List**

In [73]:
pd.Series(data = my_list) 

0    100
1    200
2    300
dtype: int64

It looks a lot like an numpy array. Except here it's very distinguished that we have an index 0 1 2 and then the actual data 100 200 300 and the key to a panda series is that you can actually specify what you want that index to be.

In [74]:
pd.Series(data=my_list,index=labels)

x    100
y    200
z    300
dtype: int64

**numpy array**

In [75]:
pd.Series(arr)

0    100
1    200
2    300
dtype: int64

In [76]:
pd.Series(arr,labels)

x    100
y    200
z    300
dtype: int64

**Dictionary**

In [77]:
pd.Series(dic)

x    100
y    200
z    300
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types. Its entries are not limited to integers. For instance, here's a `series` whose values are strings:

In [78]:
pd.Series(data=labels)

0    x
1    y
2    z
dtype: object

In [79]:
# Even functions (although unlikely that you will use this) 
#This is just to demonstrate of pandas flexibility to work with various data type
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

## Using an Index

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [80]:
ser1 = pd.Series([10,20,30,40],index = ['X', 'Y','Z', 'T'])                                   

In [81]:
ser1

X    10
Y    20
Z    30
T    40
dtype: int64

In [82]:
ser2 = pd.Series([10,20,50,40],index = ['X', 'Y','M', 'T'])                                   

In [83]:
ser2

X    10
Y    20
M    50
T    40
dtype: int64

In [84]:
ser1['X'] #just pass in the index label

10

**Operations are then also done based off of index:**

*Note:  when performing operations with a Pandas series (or almost ny numpy Panda's base object)  the integers will be converted into floats. That's so you don't accidentally lose information and maintain them.

In [85]:
ser1 + ser2

M     NaN
T    80.0
X    20.0
Y    40.0
Z     NaN
dtype: float64

#  DataFrames: creating, reading, writing

A `DataFrame` is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column.

# Creating
We are using the `pd.DataFrame()` constructor to generate these `DataFrame` objects.

In [86]:
df = pd.DataFrame(randn(4,3), index=['A','B','C','D'], columns=['X','Y','Z'])

#!Be more Professional:
#df = pd.DataFrame(randn(4,3),index='A B C D'.split(),columns='X Y Z'.split())

In [87]:
df

X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

In [88]:
#type(df['X'])

In [89]:
data = pd.DataFrame({'Course':['NPP','NPP','EDMS','EDMS','CM','CM'],
       'Person':['Bob','Sam','Amy','Vanessa','Carl','Sarah'],
       'Marks':[70,75,80,65,60,90]},
       index=['A','B','C','D','E','F'])

In [ ]:
#Every column likes a pd series with label

In [92]:
data

Course   Person  Marks
A    NPP      Bob     70
B    NPP      Sam     75
C   EDMS      Amy     80
D   EDMS  Vanessa     65
E     CM     Carl     60
F     CM    Sarah     90

# Reading and writing

Being able to create a `DataFrame` or `Series` by hand is useful. But, most of the time, we won't actually be creating our own data by hand. Instead, we'll be working with data that already exists.

**CSV** Data can be stored in any of a number of different forms and formats. By far the most basic of these is the humble CSV file. When you open a CSV file you get something that looks like this:

In [96]:
df1 = pd.read_csv('inputs/df1.csv',index_col = 0)# chose first column as index, or will generate new default index

In [97]:
df1.head()

A         B         C         D
2000-01-01  1.339091 -0.163643 -0.646443  1.041233
2000-01-02 -0.774984  0.137034 -0.882716 -2.253382
2000-01-03 -0.921037 -0.482943 -0.417100  0.478638
2000-01-04 -1.738808 -0.072973  0.056517  0.015085
2000-01-05 -0.905980  1.778576  0.381918  0.291436

The `pd.read_csv()` function is very versatile, with over 30 optional parameters you can specify. For example, you can see in this dataset that the CSV file has a built-in index, which pandas did not pick up on automatically. To make pandas use that column for the index (instead of creating a new one from scratch), we can specify an index_col.

In [ ]:
#df.to_csv('example',index=False)

**Excel** Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash.

In [ ]:
#pd.read_excel('Excel_Sample.xlsx',sheetname='Sheet1')

In [ ]:
#df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

<div class="alert alert-block alert-success" style="color:red">

You can see how to read HTML and SQL files in [Extra](./Extra.ipynb) </div>

#  Selection, Assigning data and Indexing

## Selection

Let's learn the various methods to grab data from a DataFrame.
These are the two ways of selecting a specific Series out of a `DataFrame`. 

The indexing operator `[]` does have the advantage that it can handle column names with reserved characters in them.

In [98]:
df

X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

In [99]:
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [100]:
df.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [101]:
df['Y']

A    0.628133
B    0.651118
C    0.605965
D    0.528813
Name: Y, dtype: float64

In [102]:
# Pass a list of column names
df[['Y','Z']]

Y         Z
A  0.628133  0.907969
B  0.651118 -0.319318
C  0.605965 -2.018168
D  0.528813 -0.589001

In [103]:
# SQL Syntax (NOT RECOMMENDED!)
df.Y

A    0.628133
B    0.651118
C    0.605965
D    0.528813
Name: Y, dtype: float64

In [104]:
df['Y'][0]

0.6281327087844596

### Index-based selection

Pandas indexing works in one of two paradigms. The first is index-based selection: selecting data based on its numerical position in the data. `iloc` follows this paradigm.

The second paradigm for attribute selection is the one followed by the `loc` operator: **label-based selection**. In this paradigm, it's the data index value, not its position, which matters.

Both `loc` and `iloc` are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second.

In [105]:
df.loc['A']

X    2.706850
Y    0.628133
Z    0.907969
Name: A, dtype: float64

In [106]:
df.loc['B','Y']

0.6511179479432686

In [107]:
df.loc[['A','B'],['Z','Y']]

Z         Y
A  0.907969  0.628133
B -0.319318  0.651118

In [113]:
df

X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

In [112]:
df.iloc[1]

X    0.503826
Y    0.651118
Z   -0.319318
Name: B, dtype: float64

In [108]:
df.iloc[0,:] #or df.iloc[1]

X    2.706850
Y    0.628133
Z    0.907969
Name: A, dtype: float64

In [109]:
df.iloc[:, 0]

A    2.706850
B    0.503826
C   -0.848077
D    0.740122
Name: X, dtype: float64

In [110]:
df.iloc[:3, 0]

A    2.706850
B    0.503826
C   -0.848077
Name: X, dtype: float64

In [111]:
df.iloc[[1, 2], 0]

B    0.503826
C   -0.848077
Name: X, dtype: float64

### Creating a new column:
**DataFrame Columns are just Series**

In [114]:
type(df['Z'])

pandas.core.series.Series

In [115]:
df['new'] = df['Z'] + df['Y']

In [116]:
df

X         Y         Z       new
A  2.706850  0.628133  0.907969  1.536102
B  0.503826  0.651118 -0.319318  0.331800
C -0.848077  0.605965 -2.018168 -1.412203
D  0.740122  0.528813 -0.589001 -0.060187

In [117]:
df['index_backwards'] = range(len(df), 0, -1)
df

X         Y         Z       new  index_backwards
A  2.706850  0.628133  0.907969  1.536102                4
B  0.503826  0.651118 -0.319318  0.331800                3
C -0.848077  0.605965 -2.018168 -1.412203                2
D  0.740122  0.528813 -0.589001 -0.060187                1

### Removing Columns

In [118]:
df.drop('new',axis=1)

X         Y         Z  index_backwards
A  2.706850  0.628133  0.907969                4
B  0.503826  0.651118 -0.319318                3
C -0.848077  0.605965 -2.018168                2
D  0.740122  0.528813 -0.589001                1

In [119]:
# Not inplace unless specified!
df

X         Y         Z       new  index_backwards
A  2.706850  0.628133  0.907969  1.536102                4
B  0.503826  0.651118 -0.319318  0.331800                3
C -0.848077  0.605965 -2.018168 -1.412203                2
D  0.740122  0.528813 -0.589001 -0.060187                1

In [120]:
df.drop('new',axis=1,inplace=True)
#or 
#df_newVer = df.drop('new',axis=1)

Can also drop rows this way:

In [121]:
df.drop('A',axis=0) #0 is row , 1 is column?

X         Y         Z  index_backwards
B  0.503826  0.651118 -0.319318                3
C -0.848077  0.605965 -2.018168                2
D  0.740122  0.528813 -0.589001                1

**Permanently Removing a Column**

In [122]:
del df['index_backwards']

In [123]:
df

X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [124]:
df>0

X     Y      Z
A   True  True   True
B   True  True  False
C  False  True  False
D   True  True  False

In [125]:
df[df>0]

X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118       NaN
C       NaN  0.605965       NaN
D  0.740122  0.528813       NaN

In [126]:
df[df['Z']>0] #return the rows where z at the row > 0

X         Y         Z
A  2.70685  0.628133  0.907969

In [127]:
df[df['Z']>0]['Y']

A    0.628133
Name: Y, dtype: float64

In [128]:
df[df['Z']>0][['Y','X']]

Y        X
A  0.628133  2.70685

For two conditions you can use | and & with parenthesis:

In [132]:
df[(df['X']>0) & (df['Y'] > 1)]  # Do not use and / or ; noticing the use of ()

Empty DataFrame
Columns: [X, Y, Z]
Index: []

In [133]:
df

X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

Pandas comes with a few built-in conditional selectors, two of which we will highlight here.

The first is `isin`. `isin` is lets you select data whose value "is in" a list of values.

The second is `isnull` (and its companion `notnull`). These methods let you highlight values which are (or are not) empty (`NaN`). For example, to filter out wines lacking a price tag in the dataset, here's what we would do:

In [135]:
df['Z'].notnull()

A    True
B    True
C    True
D    True
Name: Z, dtype: bool

In [134]:
df.loc[df['Z'].notnull()]  # df.loc accept true/false input

X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

### More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else.

In [136]:
# Reset to default 0,1...n index
df.reset_index()

index         X         Y         Z
0     A  2.706850  0.628133  0.907969
1     B  0.503826  0.651118 -0.319318
2     C -0.848077  0.605965 -2.018168
3     D  0.740122  0.528813 -0.589001

In [137]:
newind = 'one two three four'.split()

In [138]:
df['Hs_type'] = newind

In [139]:
df

X         Y         Z Hs_type
A  2.706850  0.628133  0.907969     one
B  0.503826  0.651118 -0.319318     two
C -0.848077  0.605965 -2.018168   three
D  0.740122  0.528813 -0.589001    four

In [140]:
df.set_index('Hs_type')

X         Y         Z
Hs_type                              
one      2.706850  0.628133  0.907969
two      0.503826  0.651118 -0.319318
three   -0.848077  0.605965 -2.018168
four     0.740122  0.528813 -0.589001

In [141]:
df.set_index('Hs_type',inplace=True)

<div class="alert alert-block alert-success">
    
See [Extra](./Extra.ipynb) for **Multi-Index and Index Hierarchy** </div>

#  Operations

There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category. Let's show them here in this lecture:

In [143]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['aa','cc','dd','ee']})
df.head()

col1  col2 col3
0     1   444   aa
1     2   555   cc
2     3   666   dd
3     4   444   ee

### Info on Unique Values

In [144]:
df['col2'].unique()

array([444, 555, 666])

In [145]:
df['col2'].nunique()

3

In [146]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

### Duplications

In [147]:
df.duplicated()#.sum()

0    False
1    False
2    False
3    False
dtype: bool

#### Drop duplication

In [148]:
df.drop_duplicates(inplace=True)

### statistical information

This method generates a high-level summary of the attributes of the given column. It is type-aware, meaning that its output changes based on the data type of the input. The output above only makes sense for numerical data; for string data here's what we get:

In [149]:
df['col2'].mean() #.std() #.median()

527.25

#### Summary Function
Pandas provides many simple *summary functions* (not an official name) which restructure the data in some useful way. For example, consider the `describe()` method:

In [150]:
df.describe()

col1        col2
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

# <span style="color:red">MAP</span> 

A **map** is a term, borrowed from mathematics, for a function that takes one set of values and "maps" them to another set of values. In data science we often have a need for creating new representations from existing data, or for transforming data from the format it is in now to the format that we want it to be in later. Maps are what handle this work, making them extremely important for getting your work done!

There are two mapping methods that you will use often.

`map()` is the first, and slightly simpler one. For example, suppose that we wanted to remean the scores the wines received to 0. We can do this as follows:

In [151]:
df_mean = df['col1'].mean()
df['col1'].map(lambda p: p - df_mean)

0   -1.5
1   -0.5
2    0.5
3    1.5
Name: col1, dtype: float64

### Applying Functions  (similar to map)

In [154]:
df

col1  col2 col3
0     1   444   aa
1     2   555   cc
2     3   666   dd
3     4   444   ee

In [152]:
def times2(x):
    return x*2

In [153]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [156]:
df['col3'].apply(len)

0    2
1    2
2    2
3    2
Name: col3, dtype: int64

In [157]:
df['col2'].sum()

2109

## Data Types 

You can use the `dtype` property to grab the type of a specific column. Or you can use `dtypes` to see all data types of columns

In [158]:
df['col2'].dtype 

dtype('int64')

In [159]:
df.dtypes

col1     int64
col2     int64
col3    object
dtype: object

Data types tell us something about how pandas is storing the data internally. `float64` means that it's using a 64-bit floating point number; `int64` means a similarly sized integer instead, and so on.

One peculiarity to keep in mind (and on display very clearly here) is that columns consisting entirely of strings do not get their own type; they are instead given the object type.

# <span style="color:red">Note this</span> 
It's possible to convert a column of one type into another wherever such a conversion makes sense by using the `astype()` function. For example, we may transform the points column from its existing `int64` data type into a `float64` data type:

In [160]:
df['col2'].astype('float64')

0    444.0
1    555.0
2    666.0
3    444.0
Name: col2, dtype: float64

## Missing Values

Entries missing values are given the value `NaN`, short for "Not a Number". For technical reasons these `NaN` values are always of the `float64` `dtype`.

Pandas provides some methods specific to missing data. To select `NaN` entries you can use `pd.isnull()` (or its companion `pd.notnull()`). This is meant to be used thusly:

In [161]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['aaa','bbb','ccc','ddd']})
df.head()

col1   col2 col3
0   1.0    NaN  aaa
1   2.0  555.0  bbb
2   3.0  666.0  ccc
3   NaN  444.0  ddd

In [162]:
df.isnull()#.sum()

col1   col2   col3
0  False   True  False
1  False  False  False
2  False  False  False
3   True  False  False

In [163]:
df.fillna('FILL')

col1   col2 col3
0   1.0   FILL  aaa
1   2.0  555.0  bbb
2   3.0  666.0  ccc
3  FILL  444.0  ddd

In [190]:
df

A   B  C  D
0  Class1  M1  x  1
1  Class1  M1  y  3
2  Class1  M2  x  2
3  Class2  M2  y  5
4  Class2  M1  x  4
5  Class2  M1  y  1

In [188]:
data = {'A':['Class1','Class1','Class1','Class2','Class2','Class2'],
     'B':['M1','M1','M2','M2','M1','M1'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C            x    y
A      B           
Class1 M1  1.0  3.0
       M2  2.0  NaN
Class2 M1  4.0  1.0
       M2  NaN  5.0

In [165]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [166]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [167]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [168]:
df.dropna(thresh=2) #At least have 2 remained?

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [169]:
df.fillna(value='FILL VALUE')

A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [170]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

The `replace()` method is worth mentioning here because it's handy for replacing missing data which is given some kind of sentinel value in the dataset: things like "Unknown", "Undisclosed", "Invalid", and so on.

# Groupby

The `groupby()` method allows you to group rows of data together and call aggregate functions.

In [192]:
# Create dataframe
data = pd.DataFrame({'Course':['NPP','NPP','EDMS','EDMS','CM','CM'],
       'Person':['Bob','Sam','Amy','Vanessa','Carl','Sarah'],
       'Marks':[70,75,80,65,60,90]},
       index=['A','B','C','D','E','F'])

In [193]:
df = pd.DataFrame(data)

** Now you can use the .groupby() method to group rows together based off of a column name. For instance let's group based off of Company. This will create a DataFrameGroupBy object:**

In [173]:
df.groupby('Course')

You can save this object as a new variable:

In [174]:
by_course = df.groupby("Course")

And then call aggregate methods off the object:

In [175]:
by_course.mean()

/var/folders/wb/x375xcqd3p31cgn8w1m_xggm0000gp/T/ipykernel_18743/3557525390.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  by_course.mean()


Marks
Course       
CM       75.0
EDMS     72.5
NPP      72.5

In [178]:
df.groupby('Course').mean()

/var/folders/wb/x375xcqd3p31cgn8w1m_xggm0000gp/T/ipykernel_18743/1924564367.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Course').mean()


Marks
Course       
CM       75.0
EDMS     72.5
NPP      72.5

In [179]:
by_course.std() #max() #min()

/var/folders/wb/x375xcqd3p31cgn8w1m_xggm0000gp/T/ipykernel_18743/2396688855.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  by_course.std() #max() #min()


Marks
Course           
CM      21.213203
EDMS    10.606602
NPP      3.535534

In [183]:
df

Course   Person  Marks
A    NPP      Bob     70
B    NPP      Sam     75
C   EDMS      Amy     80
D   EDMS  Vanessa     65
E     CM     Carl     60
F     CM    Sarah     90

In [180]:
by_course.count()

Person  Marks
Course               
CM           2      2
EDMS         2      2
NPP          2      2

In [181]:
by_course.describe()

Marks                                                 
       count  mean        std   min    25%   50%    75%   max
Course                                                       
CM       2.0  75.0  21.213203  60.0  67.50  75.0  82.50  90.0
EDMS     2.0  72.5  10.606602  65.0  68.75  72.5  76.25  80.0
NPP      2.0  72.5   3.535534  70.0  71.25  72.5  73.75  75.0

In [184]:
by_course.describe().transpose()

Course              CM       EDMS        NPP
Marks count   2.000000   2.000000   2.000000
      mean   75.000000  72.500000  72.500000
      std    21.213203  10.606602   3.535534
      min    60.000000  65.000000  70.000000
      25%    67.500000  68.750000  71.250000
      50%    75.000000  72.500000  72.500000
      75%    82.500000  76.250000  73.750000
      max    90.000000  80.000000  75.000000

In [185]:
by_course.describe().transpose()['NPP']

Marks  count     2.000000
       mean     72.500000
       std       3.535534
       min      70.000000
       25%      71.250000
       50%      72.500000
       75%      73.750000
       max      75.000000
Name: NPP, dtype: float64

Another groupby() method worth mentioning is agg(), which lets you run a bunch of different functions on your DataFrame simultaneously. For example, we can generate a simple statistical summary of the dataset as follows:

In [195]:
df.groupby(['Course']).agg([len, min, max])

Person                Marks        
          len   min      max   len min max
Course                                    
CM          2  Carl    Sarah     2  60  90
EDMS        2   Amy  Vanessa     2  65  80
NPP         2   Bob      Sam     2  70  75

# Merging, Joining, and Concatenating

There are 3 main ways of combining DataFrames together: Merging, Joining and Concatenating. In this lecture we will discuss these 3 methods with examples.

In [196]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [197]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [198]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

## Concatenation

Concatenation basically glues together DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use **pd.concat** and pass in a list of DataFrames to concatenate together:

In [199]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [200]:
pd.concat([df1,df2,df3],axis=1)  #Axis = 1 means concat based on row index?

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [201]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

## Merging

The **merge** function allows you to merge DataFrames together using a similar logic as merging SQL Tables together. For example:

In [203]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [202]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [204]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [205]:
pd.merge(left, right, on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [206]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [207]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [208]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

## Joining
Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

In [209]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [210]:
left.join(right)  # keep the index of left

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [211]:
left.join(right, how='outer')  #remain both the index

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

<div class="alert alert-block alert-success">
    
See **Built-in visualization features**
and **Timeseries with Pandas** in [Extra](./Extra.ipynb) </div>

# Further reading and refrences

 For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

 [Pandas extra](https://pandas.pydata.org/pandas-docs/stable/getting_started/tutorials.html).

Further, if you are interested in data science and machine learning then you need to know about Kaggle. You will use it a few times throughout the year. An introduction can be found:

[![Two](http://img.youtube.com/vi/TNzDMOg_zsw/0.jpg)](https://youtu.be/TNzDMOg_zsw)